server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.23.129:1111  #配置换成nginx的1111端口 做集群 转发到 3个nacos 端口中
  #        server-addr: localhost:8848 #配置Nacos地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.23.129:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wsy3880703
mybatis:
  mapper-locations: classpath:mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'




