server:
  port: 3344
spring:
  application:
    name: cloud-config-center   #注册进eureka 服务器的微服务名称
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wang-siyuan1997/sprincloud-config
          search-paths:
          #搜索目录
            - sprincloud-config
          #读取分支
#          username: wangsiyuan1997
#          password: Wsy3880703
      label: master
  #Rabbit MQ 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    virtual-host: my_vhost
eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

##rabbit MQ 相关配置，暴露bus 刷新配置端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
