server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名称进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址 （写死）
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址 （动态 获取注册中心的 用户名进行动态路由）
          predicates:
            - Path=/payment/select/**   #断言,路径相匹配的进行路由

        - id: payment_routh2        #路由id，没有固定规则但是要求唯一，建议配合服务名使用
#          uri: http://localhost:8001  #匹配后的路由地址 （写死）
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址 （动态 获取注册中心的 用户名进行动态路由）
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#            - Cookie=username,wsy
#            - Between=2022-01-21T22:09:44.527569900+08:00[Asia/Shanghai],2022-01-21T23:09:44.527569900+08:00[Asia/Shanghai]
#            - After=2022-01-21T21:09:44.527569900+08:00[Asia/Shanghai]
#            - Before=2022-01-21T21:09:44.527569900+08:00[Asia/Shanghai]

#            2022-01-21T20:09:44.527569900+08:00[Asia/Shanghai]



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


